kind: Service
apiVersion: v1
metadata:
  name: ${REPO_NAME}
spec:
  selector:
    app: ${REPO_NAME}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ${REPO_NAME}
  labels:
    app: ${REPO_NAME}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${REPO_NAME}
  template:
    metadata:
      labels:
        app: ${REPO_NAME}
    spec:
      containers:
      - name: ${REPO_NAME}
        image: gcr.io/${GOOGLE_PROJECT_ID}/${REPO_NAME}:${CIRCLE_SHA1}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
